#ifndef __S2_AES_OOTBF_XML_FUNCTIONS_V2_0_0_H__
#define __S2_AES_OOTBF_XML_FUNCTIONS_V2_0_0_H__



/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__ROOM
*/
#define ROOM__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN 32
#define ROOM__S2_AES_OOTBF_XML_Functions_v2_0_0_ID$_STRING_MAX_LEN 6
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM )
{
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM__NAME$, ROOM__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM__NAME$ );
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM__ID$, ROOM__S2_AES_OOTBF_XML_Functions_v2_0_0_ID$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM__ID$ );
   unsigned short ROOM__OUTPUT;
   unsigned short ROOM__SWITCHER;
   unsigned short ROOM__BASS;
   unsigned short ROOM__TREBLE;
   unsigned short ROOM__BALANCE;
   unsigned short ROOM__MONO;
   unsigned short ROOM__LOUD;
   unsigned short ROOM__MINVOL;
   unsigned short ROOM__MAXVOL;
   unsigned short ROOM__STARTVOL;
   unsigned short ROOM__INTERRUPTVOL;
   unsigned short ROOM__DONOTDISTURB;
};

/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__SOURCE
*/
#define SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN 32
#define SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_STRING_MAX_LEN 6
#define SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_COMMANDFILE$_STRING_MAX_LEN 50
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE )
{
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__NAME$, SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__NAME$ );
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__ROOMID$, SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__ROOMID$ );
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__COMMANDFILE$, SOURCE__S2_AES_OOTBF_XML_Functions_v2_0_0_COMMANDFILE$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE__COMMANDFILE$ );
   unsigned short SOURCE__INPUT;
   unsigned short SOURCE__TYPE;
   unsigned short SOURCE__GAIN;
   unsigned short SOURCE__VISIBLE;
   unsigned short SOURCE__MODELID;
   unsigned short SOURCE__PARENTID;
   unsigned short SOURCE__NETID;
   unsigned short SOURCE__CONTROLENTRYID;
   unsigned short SOURCE__ENABLED;
};

/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__GROUP
*/
#define GROUP__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP )
{
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP__NAME$, GROUP__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP__NAME$ );
   unsigned short GROUP__ID;
   unsigned short GROUP__SOURCE;
   CREATE_INTARRAY1D( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP__ROOMS, 24 );;
   DECLARE_INTARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP__ROOMS );
};

/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__DEVICE
*/
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, DEVICE )
{
   unsigned short DEVICE__ISPRESENT;
   unsigned short DEVICE__INPUTSTARTSAT;
};

/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__SYSTEM
*/
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SYSTEM )
{
   unsigned short SYSTEM__LOCATION;
   unsigned short SYSTEM__NUMROOMS;
   CREATE_INTARRAY1D( S2_AES_OOTBF_XML_Functions_v2_0_0, SYSTEM__KEYMAP, 6 );;
   DECLARE_INTARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, SYSTEM__KEYMAP );
};

/*
* STRUCTURE S2_AES_OOTBF_XML_Functions_v2_0_0__INTERFACE
*/
#define INTERFACE__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN 32
START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, INTERFACE )
{
   CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, INTERFACE__NAME$, INTERFACE__S2_AES_OOTBF_XML_Functions_v2_0_0_NAME$_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, INTERFACE__NAME$ );
   unsigned short INTERFACE__NETID;
   unsigned short INTERFACE__LIBRARYID;
   unsigned short INTERFACE__OUTPUT;
};


/*
* Constructor and Destructor
*/
int S2_AES_OOTBF_XML_Functions_v2_0_0_ROOM_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_ROOM_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, ROOM ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCE_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCE_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SOURCE ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_GROUP_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_GROUP_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, GROUP ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_DEVICE_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, DEVICE ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_DEVICE_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, DEVICE ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_SYSTEM_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SYSTEM ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_SYSTEM_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, SYSTEM ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_INTERFACE_Constructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, INTERFACE ) * me, int nVerbose );
int S2_AES_OOTBF_XML_Functions_v2_0_0_INTERFACE_Destructor ( START_STRUCTURE_DEFINITION( S2_AES_OOTBF_XML_Functions_v2_0_0, INTERFACE ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVESETTINGS_DIG_INPUT 0
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_STARTUPOOTBF_DIG_INPUT 1
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_STARTUPSYSTEMBUILDER_DIG_INPUT 2
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_STARTUPCUSTOM_DIG_INPUT 3
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_RESTOREDEFAULTS_DIG_INPUT 4
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_RESTOREAUDIODEFAULTS_DIG_INPUT 5

#define __S2_AES_OOTBF_XML_Functions_v2_0_0_APADOFFLINE_DIG_INPUT 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_APADOFFLINE_ARRAY_LENGTH 12
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADOFFLINE_DIG_INPUT 18
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADOFFLINE_ARRAY_LENGTH 12

/*
* ANALOG_INPUT
*/
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_TUNERFORMATIN_ANALOG_INPUT 2
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_NUMBEROFROOMSIN_ANALOG_INPUT 3

#define __S2_AES_OOTBF_XML_Functions_v2_0_0_MODELNAME$_STRING_INPUT 0
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_MODELNAME$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __MODELNAME$, __S2_AES_OOTBF_XML_Functions_v2_0_0_MODELNAME$_STRING_MAX_LEN );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_FILENAME$_STRING_INPUT 1
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_FILENAME$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __FILENAME$, __S2_AES_OOTBF_XML_Functions_v2_0_0_FILENAME$_STRING_MAX_LEN );


#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADMAPIN_ANALOG_INPUT 4
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADMAPIN_ARRAY_LENGTH 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBASSIN_ANALOG_INPUT 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBASSIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMTREBLEIN_ANALOG_INPUT 34
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMTREBLEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBALANCEIN_ANALOG_INPUT 58
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBALANCEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMONOIN_ANALOG_INPUT 82
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMONOIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMLOUDNESSIN_ANALOG_INPUT 106
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMLOUDNESSIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMINVOLUMEIN_ANALOG_INPUT 130
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMINVOLUMEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMAXVOLUMEIN_ANALOG_INPUT 154
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMAXVOLUMEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMSTARTVOLUMEIN_ANALOG_INPUT 178
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMSTARTVOLUMEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMINTERRUPTVOLUMEIN_ANALOG_INPUT 202
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMINTERRUPTVOLUMEIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMDONOTDISTURBIN_ANALOG_INPUT 226
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMDONOTDISTURBIN_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEENABLEDIN_ANALOG_INPUT 250
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEENABLEDIN_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SLOTID_ANALOG_INPUT 260
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SLOTID_ARRAY_LENGTH 3
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCETYPEIN_ANALOG_INPUT 263
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCETYPEIN_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTROOMNAME$_STRING_INPUT 273
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTROOMNAME$_ARRAY_NUM_ELEMS 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTROOMNAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTROOMNAME$, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTROOMNAME$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTROOMNAME$_ARRAY_NUM_CHARS );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTSOURCENAME$_STRING_INPUT 297
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTSOURCENAME$_ARRAY_NUM_ELEMS 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTSOURCENAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTSOURCENAME$, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTSOURCENAME$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTSOURCENAME$_ARRAY_NUM_CHARS );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTGROUPNAME$_STRING_INPUT 307
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTGROUPNAME$_ARRAY_NUM_ELEMS 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTGROUPNAME$_ARRAY_NUM_CHARS 32
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTGROUPNAME$, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTGROUPNAME$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_INPUTGROUPNAME$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_FILEREADDONE_DIG_OUTPUT 0
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_RESTOREDEFAULTSDONE_DIG_OUTPUT 1
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_RESTOREAUDIODEFAULTSDONE_DIG_OUTPUT 2
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SYSTEMBUILDERFILEREADERROR_DIG_OUTPUT 3


/*
* ANALOG_OUTPUT
*/
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_TUNERFORMATOUT_ANALOG_OUTPUT 0
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_NUMBEROFROOMSOUT_ANALOG_OUTPUT 1


#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBASS_ANALOG_OUTPUT 2
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBASS_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMTREBLE_ANALOG_OUTPUT 26
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMTREBLE_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBALANCE_ANALOG_OUTPUT 50
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMBALANCE_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMONO_ANALOG_OUTPUT 74
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMONO_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMLOUDNESS_ANALOG_OUTPUT 98
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMLOUDNESS_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMINVOLUME_ANALOG_OUTPUT 122
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMINVOLUME_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMAXVOLUME_ANALOG_OUTPUT 146
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMMAXVOLUME_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMSTARTVOLUME_ANALOG_OUTPUT 170
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMSTARTVOLUME_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMINTERRUPTVOLUME_ANALOG_OUTPUT 194
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMINTERRUPTVOLUME_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMDONOTDISTURB_ANALOG_OUTPUT 218
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMDONOTDISTURB_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCETYPEOUT_ANALOG_OUTPUT 242
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCETYPEOUT_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEGAIN_ANALOG_OUTPUT 252
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEGAIN_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEMODELID_ANALOG_OUTPUT 262
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEMODELID_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEPARENTID_ANALOG_OUTPUT 272
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEPARENTID_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCENETID_ANALOG_OUTPUT 282
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCENETID_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEENABLED_ANALOG_OUTPUT 292
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEENABLED_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPSOURCE_ANALOG_OUTPUT 302
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPSOURCE_ARRAY_LENGTH 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPROOMSLOW_ANALOG_OUTPUT 308
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPROOMSLOW_ARRAY_LENGTH 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPROOMSHIGH_ANALOG_OUTPUT 314
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SAVEDGROUPROOMSHIGH_ARRAY_LENGTH 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADMAPOUT_ANALOG_OUTPUT 320
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_KEYPADMAPOUT_ARRAY_LENGTH 6
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMNAME$_STRING_OUTPUT 326
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMNAME$_ARRAY_LENGTH 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCENAME$_STRING_OUTPUT 350
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCENAME$_ARRAY_LENGTH 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_GROUPNAME$_STRING_OUTPUT 360
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_GROUPNAME$_ARRAY_LENGTH 6

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCECONTROLENTRYID, 10 );;
CREATE_INTARRAY1D( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMOUTPUT, 24 );;
CREATE_INTARRAY1D( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMSWITCHER, 24 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ADAGIO_DATA_FILE_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __ADAGIO_DATA_FILE, __S2_AES_OOTBF_XML_Functions_v2_0_0_ADAGIO_DATA_FILE_STRING_MAX_LEN );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_CREATEDBY$_STRING_MAX_LEN 64
CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __CREATEDBY$, __S2_AES_OOTBF_XML_Functions_v2_0_0_CREATEDBY$_STRING_MAX_LEN );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_INTERFACEBLOCK$_STRING_MAX_LEN 7000
CREATE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __INTERFACEBLOCK$, __S2_AES_OOTBF_XML_Functions_v2_0_0_INTERFACEBLOCK$_STRING_MAX_LEN );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_ARRAY_NUM_ELEMS 24
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMID$, __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_ROOMID$_ARRAY_NUM_CHARS );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEROOMID$_ARRAY_NUM_ELEMS 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEROOMID$_ARRAY_NUM_CHARS 6
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCEROOMID$, __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEROOMID$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCEROOMID$_ARRAY_NUM_CHARS );
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCECOMMANDFILE$_ARRAY_NUM_ELEMS 10
#define __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCECOMMANDFILE$_ARRAY_NUM_CHARS 50
CREATE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCECOMMANDFILE$, __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCECOMMANDFILE$_ARRAY_NUM_ELEMS, __S2_AES_OOTBF_XML_Functions_v2_0_0_SOURCECOMMANDFILE$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __APADOFFLINE );
   DECLARE_IO_ARRAY( __KEYPADOFFLINE );
   DECLARE_IO_ARRAY( __KEYPADMAPIN );
   DECLARE_IO_ARRAY( __ROOMBASSIN );
   DECLARE_IO_ARRAY( __ROOMTREBLEIN );
   DECLARE_IO_ARRAY( __ROOMBALANCEIN );
   DECLARE_IO_ARRAY( __ROOMMONOIN );
   DECLARE_IO_ARRAY( __ROOMLOUDNESSIN );
   DECLARE_IO_ARRAY( __ROOMMINVOLUMEIN );
   DECLARE_IO_ARRAY( __ROOMMAXVOLUMEIN );
   DECLARE_IO_ARRAY( __ROOMSTARTVOLUMEIN );
   DECLARE_IO_ARRAY( __ROOMINTERRUPTVOLUMEIN );
   DECLARE_IO_ARRAY( __ROOMDONOTDISTURBIN );
   DECLARE_IO_ARRAY( __SOURCEENABLEDIN );
   DECLARE_IO_ARRAY( __SLOTID );
   DECLARE_IO_ARRAY( __SOURCETYPEIN );
   DECLARE_IO_ARRAY( __ROOMBASS );
   DECLARE_IO_ARRAY( __ROOMTREBLE );
   DECLARE_IO_ARRAY( __ROOMBALANCE );
   DECLARE_IO_ARRAY( __ROOMMONO );
   DECLARE_IO_ARRAY( __ROOMLOUDNESS );
   DECLARE_IO_ARRAY( __ROOMMINVOLUME );
   DECLARE_IO_ARRAY( __ROOMMAXVOLUME );
   DECLARE_IO_ARRAY( __ROOMSTARTVOLUME );
   DECLARE_IO_ARRAY( __ROOMINTERRUPTVOLUME );
   DECLARE_IO_ARRAY( __ROOMDONOTDISTURB );
   DECLARE_IO_ARRAY( __SOURCETYPEOUT );
   DECLARE_IO_ARRAY( __SOURCEGAIN );
   DECLARE_IO_ARRAY( __SOURCEMODELID );
   DECLARE_IO_ARRAY( __SOURCEPARENTID );
   DECLARE_IO_ARRAY( __SOURCENETID );
   DECLARE_IO_ARRAY( __SOURCEENABLED );
   DECLARE_IO_ARRAY( __SAVEDGROUPSOURCE );
   DECLARE_IO_ARRAY( __SAVEDGROUPROOMSLOW );
   DECLARE_IO_ARRAY( __SAVEDGROUPROOMSHIGH );
   DECLARE_IO_ARRAY( __KEYPADMAPOUT );
   DECLARE_IO_ARRAY( __ROOMNAME$ );
   DECLARE_IO_ARRAY( __SOURCENAME$ );
   DECLARE_IO_ARRAY( __GROUPNAME$ );
   unsigned short __READBUSY;
   unsigned short __WRITEBUSY;
   unsigned short __NEEDWRITE;
   unsigned short __SYSTEMTYPE;
   DECLARE_INTARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCECONTROLENTRYID );
   DECLARE_INTARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMOUTPUT );
   DECLARE_INTARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMSWITCHER );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __ADAGIO_DATA_FILE );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __CREATEDBY$ );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __INTERFACEBLOCK$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __ROOMID$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCEROOMID$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __SOURCECOMMANDFILE$ );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __MODELNAME$ );
   DECLARE_STRING_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0, __FILENAME$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTROOMNAME$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTSOURCENAME$ );
   DECLARE_STRING_ARRAY( S2_AES_OOTBF_XML_Functions_v2_0_0, __INPUTGROUPNAME$ );
   struct FileInfo_s __G_FIDATAFILE;
};

START_NVRAM_VAR_STRUCT( S2_AES_OOTBF_XML_Functions_v2_0_0 )
{
};



#endif //__S2_AES_OOTBF_XML_FUNCTIONS_V2_0_0_H__

